server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://localhost:3306/db_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: